export const ADD_LETTER = 'ADD_LETTER'
export const DRAW_ADD_LETTER = 'DRAW_ADD_LETTER'
export const SUCCESS_ADD_LETTER = 'SUCCESS_ADD_LETTER'
export const FAILED_ADD_LETTER = 'FAILED_ADD_LETTER'
export const DRAW_LOAD_BOOK = 'DRAW_LOAD_BOOK'
export const DRAW_LOAD_BORROWING = 'DRAW_LOAD_BORROWING'

export const SUCCESS_DELETE_LETTER = 'SUCCESS_DELETE_LETTER'
export const FAILED_DELETE_LETTER = 'FAILED_DELETE_LETTER'

export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const FAILED_LOGIN = 'FAILED_LOGIN'

export const SUCCESS_REGISTER = 'SUCCESS_REGISTER'
export const FAILED_REGISTER = 'FAILED_REGISTER'
